name: CustomPlayerEffects
version: '1.0.0'
main: me.touchie771.customPlayerEffects.CustomPlayerEffects
api-version: '1.21'
authors: [ Touchie771 ]
description: A plugin that allows each player to customize how the server world looks.

permissions:
  customplayereffects.*:
    description: Grants access to all CustomPlayerEffects features
    default: op
    children:
      customplayereffects.time: true
      customplayereffects.weather: true
      customplayereffects.fly: true
      customplayereffects.speed: true
      customplayereffects.potion: true
  
  customplayereffects.time:
    description: Allows using the /settime command
    default: op
  
  customplayereffects.weather:
    description: Allows using the /setweather command
    default: op
  
  customplayereffects.fly:
    description: Allows using the /fly command
    default: op
  
  customplayereffects.speed:
    description: Allows using the /speed command
    default: op
  
  customplayereffects.potion:
    description: Allows using the /setpotion command
    default: op