name: CustomPlayerEffects
version: '1.0.0'
main: me.touchie771.customPlayerEffects.CustomPlayerEffects
api-version: '1.21'
authors: [ Touchie771 ]
description: A plugin that allows each player to customize how the server world looks.